### ISSUE TITLE
Feature Request : Add a way to delete a specific route from the watch

### ISSUE THREAD

**Issue by ABelliqueux** [scubajorgen/TomTomWatch#10]
If possible, add a way to remove a specific route from the watch ?

Also, maybe relabel the "Erase" button to "Erase all" ?

Thanks again, great work, so glad I can get rid of mysports !

Cheers

**Comment by scubajorgen** [comment]
That would be quite some change. What I can do is plot the file ID in the list. You can use the debug menu to erase the indicated file. It's a bit tricky because if you delete the wrong files you might damage your watch. Therefore it's in the debug menu which is not enabled by default

**Comment by scubajorgen** [comment]
Another thing is that you can upload as many routes as you want, but the watch only presents 15...

**Comment by scubajorgen** [comment]
Better support for routes/track planning  in version 1.5
