### ISSUE TITLE
TrackSmoother not working ?

### ISSUE THREAD

**Issue by ABelliqueux** [scubajorgen/TomTomWatch#11]
Hi, 

Maybe I'm not doing this right, but it seems there's a problem with the "Smooth" track option.
FWIW I'm using a Tomtom Runner 3.

Problem :

When trying to check the "smooth" option in the software, the track list empties and prevents from saving the smoothed track.

How to reproduce : 

1. Open TomTomWatch with or without watch connected.
2. Click "Load TTBIN". The track list and the map should update, as well as the "GPX File" field on the left part of the window.
3. Check "Smooth" . The track list and the map are now blank.

If you check the "Smooth" option BEFORE loading the TTBIN, you are able to export a GPX file, but ~~it is identical to a file exported without the option~~ I am not sure it works that way. I get no message in the terminal. 

Just saw the debug part on software's page. Tried it, but nothing came up...

**Comment by scubajorgen** [comment]
You have to choose to use the option before downloading. Smoothing is applied during download. It is a feature that the list is emptied when changing it after download, because you have to re-download for the option to take effect
