### ISSUE TITLE
Monospaced font for output textarea?

### ISSUE THREAD

**Issue by heikojansen** [scubajorgen/TomTomWatch#12]
I do not know if this is just a symptom of a badly configured setting in my environment (openSUSE Tumbleweed) but the output textarea at the bottom of the app window does not use a monospaced font for me. 
Doing so would certainly increase the readability of tabular data presented there.
Does the TomTomWatch code try to enforce a monospaced font there? 
If yes: Do you know what setting might be responsible for the misbehavior in my environment?
If no: would you consider adding such code?

**Comment by heikojansen** [comment]
I'm using TomTomWatch Release 1.4
Java is:

    ~/TomTomWatch> java -version
    openjdk version "11-internal" 2018-09-25
    OpenJDK Runtime Environment (build 11-internal+24-suse-1.1-x8664)
    OpenJDK 64-Bit Server VM (build 11-internal+24-suse-1.1-x8664, mixed mode)

![ttw_20180808_160301](https://user-images.githubusercontent.com/295487/43842305-5ab1d866-9b25-11e8-9e9e-6d4a0b616bd5.png)

I run TTW like so as normal user (i.e.: not root):

    ~/TomTomWatch> java -jar ./TomTomWatch-1.4.jar

Unfortunately I do not use Java as a developer so I have no idea which packages or other components may be required.

**Comment by scubajorgen** [comment]
I'll have a look at it. Will take a fewxweeks though

**Comment by scubajorgen** [comment]
In the software I switched to fonts incorporated in Oracle Java (like Lucida) in order to have the same layout under Windows as under Linux. Unfortunately, the OpenJDK does not incorporate these Java fonts (probably a license issue, http://mail.openjdk.java.net/pipermail/discuss/2017-November/004630.html). Apparently Java chooses some default font, which in case of the large text box is not a mono-spaced font.

I have to look for a solution (incorporate the fonts in TomTomWatch?).

**Comment by heikojansen** [comment]
Hmm, while googling ab bit I've come across various hints on using "logical" fonts in Java which are automatically mapped to some locally installed font (so you cannot guarantee identical looks on different systems using this mechanism).
One of those logical fonts is named "Monospaced" (```new Font("Monospaced", Font.PLAIN, 12);```), so should be appropriate here.
Maybe that helps?

**Comment by heikojansen** [comment]
Well, it does not look identical on my system now anyway since unless you add the fonts to the TomTomWatch distribution you still cannot guarantee the same looks ;-)
Does Java let you detect if the font you'd like to use cannot be found? If so, then imho you should at least use the logical font as fallback.
