### ISSUE TITLE
Google Maps : Can't get input stream from URL!

### ISSUE THREAD

**Issue by ABelliqueux** [scubajorgen/TomTomWatch#13]
Hi, 

In 1.4, the map does'nt show anymore when uploading a route. The error in a terminal is :

> ERROR: Unable to get Google map: Can't get input stream from URL!

I suspect this comes from a change in google apis, as I get this message when trying to paste the generated URL in a browser : 

> The Google Maps Platform server rejected your request. You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account

GPSmaster uses OSM  via Mapnik. I think the relevant code is here : https://github.com/cl0ne/GpsMaster/tree/master/src/org/gpsmaster/osm . 
Would it be difficult to switch ?

Cheers,

**Comment by scubajorgen** [comment]
Thanx. I noticed. I'll have a look at it. So far no keys required for this google service. 
However recently google wants to make money with maps. In my online webapps I switched to OSM. However, I don't know yet if OSM will apply to this desktop app... Should be possible I guess.

**Comment by scubajorgen** [comment]
Added support for Open Street Maps. Select the map service in the tomtomwatch.properties file. Select none, osm (default) or google. In case of google a google API key is required.
