### ISSUE TITLE
Do not understand how to extract ttbin to gpx :)

### ISSUE THREAD

**Issue by matthieugeerebaert** [scubajorgen/TomTomWatch#15]
Hello and congratulation for this application

Since tomtom sport might be out of service more often, I wonder if
this application can work without any tomtom backend, just to extract ttbin to gpx from the watch

And how it works, I tried on both linux and windows but while I can have the log history, rename the device etc I can not "see" any activity like you on this screenshot, mine is still empty ( maybe more documentation ? )
http://blog.studioblueplanet.net/wp-content/uploads/2017/04/TomTomWatch-1.png

While playing with the app ( and ttwatch under linux ) while tomtom backend was in maintenance, I was able to upload activity to strava whith ttwatch, but later when tomtom came back online the activity never sync with tomtom, "I lost it". Could this occurs also with TomTomWatch ? is there a way to 're upload' an activity to tomtom ?

Many questions :) sorry for that :) but tomtom adventurer are such a reliable with long lasting battery for only 200 euros at the time ( I bought two ), so many ultra trail or 10k races with it, I really like the idea to be tomtom backend independant, just manage ttbin files :)

**Comment by scubajorgen** [comment]
First make sure the TomTom applications on PC and phone/tablet are stopped. As soon as they 'see' the watch they download and erase the ttbin files from the watch

1. Perform and record some activities
2. Connect watch
3. Start TomTomWatch
4. Press download

It first fetches the file list. It then downloads the activity/ttbin files. 

You can test if there are ttbin files on the watch by configuring debugMode in the tomtomwatch.properties. You can request the file list. Ttbin files are the files with id 0091nnnn

**Comment by scubajorgen** [comment]
⁣TomTomWatch saves the .ttbin files to the location specified in tomtomwatch.properties. I never managed to upload them with the TomTom Mysports PC application (it is suggested though). The Android app on my mobile however does the job. Simply copy the ttbin files to the TomTom directory on the phone storage and start the app. I'll let you know the exact directory. The app moves the ttbin files to a subdir 'processed'  or so.

**Comment by matthieugeerebaert** [comment]
Tried and worked perfectly, thank you very much

Discover also the subtle smooth factor and the low accuracy tracking for hikking and swimming, and so understand how we can manage a very long lasting battery with the hikking mode for almost 20hours even with external fc, while still getting 1 point per minute ( but yes accuracy was not fantastic )

Thank you, great app !
