### ISSUE TITLE
Custom workout

### ISSUE THREAD

**Issue by sbouth** [scubajorgen/TomTomWatch#17]
Hey,

is there any plan to add support to custom workout ?
it seems we need to reverse engineer 0x00BEnnnn files according to your documentation. Do you have some information about it ?

(this is a feature I would llike to add also on my android app and i'am not sure how difficult it is to reserve engineer it) 

Thx

**Comment by scubajorgen** [comment]
Reverse engineering isn't that complex. The format of this file is protobuf. Basically it is a very efficient way (in terms of size) to encode/decode data/datastructures, developed by Google. There are plenty of tools by which you can read and decode protobuf files (e.g. https://protogen.marcgravell.com/decode). From there you have to compare the data with what you see in TomTom to make sense of what the fields (identified by a number) represent. Knowing the structure, you can make the **.proto protobuf definition file**, like in my project files like /various/protobuf/route.proto. Then you can use the Google protobuf tooling (compiler) to generate code for encoding/decoding protobuf data in virtually any programming language you like.

**Comment by scubajorgen** [comment]
I reverse engineered the workout file structure. I am working at least on being able to display the workouts in the watch, in a separate branch 'workout'. I am thinking of a way to create own workouts.

**Comment by sbouth** [comment]
So GREAT !!! thanks :)

I'm going to have a look and try it with my own workout.

**Comment by sbouth** [comment]
I have tested createWorkoutListFromData with success :)
That's nice to be able to get an overview without reading all files (not sure if the same is possible for routes).

From  my workout list  I found that:
- All RUNNING have WorkoutListItem.unknown10 = 0x4181
- All CYCLING  have WorkoutListItem.unknown10 = 0x802

Those values look strange so I'm not sure if it's relevant.

**Comment by scubajorgen** [comment]
Thanx. I found out the same yesterday evening :-) and incorporated this stuff in my code. Indeed, weird looking values... And int64...

**Comment by sbouth** [comment]
I can see that your workout branch is going well from last commits :) 
I wonder if 0x00BE0000 file must be maintained by the application (desktop or mobile)  or if it's managed automatically by the watch. 

I mean, when Adding/Removing or modifying a 0x00BEnnnn file, does the watch update 0x00BE0000 automatically or is it necessary to rewrite "manually" the 0x00BE0000 ?

Do you know is some of 0x00BEnnnn are reserved or read only ?
It seems that the official mysports TT app enables only 5 customs workout for cycling + 5 customs workout for running and keep all other workout unchanged.

**Comment by scubajorgen** [comment]
0x00BE0000 isn't maintained by the watch. First, it contains data that cannot be derived from the workouts, like the RUNNING/CYCLING activity. Second, given the structure I think it makes more sense that is not generated by the watch: it contains an overview (needed fro the menu without the need for reading all the 0x00BEnnnn files) with references to the workout files. 
To be sure I checked it: wrote an addtional 0x00BE0033 file to the watch 'by hand', disconnected the watch from the PC, reconnected, downloaded 0x00BE0000: it doesn't contain a reference to the new file.

I believe there is no reservation. I changed 0x00BE0001 using tomtom mysports (I altered the intensity level). After that it became 0x00BE0036 or so, resulting in a 'missing' 0x00BE0001. 
It might be that there is a limit to the number of files, e.g. max 5 to each type. I guess I found something similar: a limit of 15 routes (not entirely sure...). I guess there is only one way to find out :-) 

Thank you so much for the file size hint. It gave me a headache yesterday. I assumed it to be bitfields, but I could not find it to be dependent consistently on anything... So I abandoned the assumption.  This is the last field I was looking for :-). The other unknowns seem to be constant...

**Comment by sbouth** [comment]
Your welcome for the file size, I'm glad I could help at least for this.

Thanks for your reply about 0x00BE0000, it's clear.

**Comment by scubajorgen** [comment]
Hum.. The 16 byte arrays appear to be MD5 hashes. The one that only occurs in 0x00BE0000 and not in  the workout files is the MD5 hash of the workout file. If is not correct, the workout won't show up on the watch.
The MD5 hash that occurs in the 0x00BE0000 and the workout files is not clear to me. It does not appear to have effect....

**Comment by sbouth** [comment]
I had no time to work on this project recently but something came to my mind.
What's happen to the other id when changing only the intensity of a workout ?
I tought it could stay unchanged but really I have not tried and don't know....

**Comment by scubajorgen** [comment]
Good thinking. My first idea was also that the other 'ID' was an MD5 on part of the content, for example on the workout steps. However, if you change them, the 'ID' remains unaltered. Its value does not seem to have any effect on the validation by the watch, even if you make the value in 0x00BE0000 different from the value in the corresponding 0x00BEnnnn workout file. I therefore left it as 'UID' identifying the workout, but its meaning is unclear.

Another finding: if you upload more than 5 workouts of the same type to the watch, only the first 5 are shown. Only 5 items fit on the display. The watch doesn't appear to have a scroll function. That limits the workouts to 6x5=30 workouts per activity  (running/cycling).

My software now supports download to JSON and upload from JSON, including redefinition of the HR Zones,  as a 'low budget' alternative to a fancy user interface.

**Comment by scubajorgen** [comment]
Functionality to export and import custom workouts released in version 1.6
