### ISSUE TITLE
Watch unresponsive 

### ISSUE THREAD

**Issue by Jacquers** [scubajorgen/TomTomWatch#19]
Have you ever experienced the watch stuck on the clock screen (time still changes) and not responding to any button presses? It doesn't connect via USB anymore either. I've tried the official reset procedure of holding the down button and then connecting it, but it doesn't enter the recovery mode. There doesn't seem to be anything I can do except wait for the battery to run down and then hopefully it will reset once powered on again. A bit silly that there isn't another way to power it down. I have the original Multisport. Wondering if you may have any other tips to try? Thanks.

**Comment by Jacquers** [comment]
I think it might have gotten some moisture inside after I rinsed it off after cycling. Today it started responding again, although erratically. Then later it showed the reset screen and now it's ok after doing the reset 👍 I see there are some commits after v1.5. Will you be putting a new compiled version on your site? Thanks :)

**Comment by scubajorgen** [comment]
Sorry for the late response. Good you solved the problem. I never encountered such a thing.
I'll have all look at the new release

**Comment by Jacquers** [comment]
It's still misbehaving, but I think it's an issue with the watch itself (physically) due to the contacts of the buttons, probably because of moisture. I'm hoping it dries out and behaves again. Otherwise I might open it up and try to clean it.
