### ISSUE TITLE
Serial Number Unknown

### ISSUE THREAD

**Issue by Jacquers** [scubajorgen/TomTomWatch#20]
My watch is the original Multisport. Using software v1.5 it doesn't pick up the serial number. The TomTom app does. Not a big issue though.

**Comment by scubajorgen** [comment]
This is a pain in the ass. I use a library for USB communication that exhibits this problem. You can work around by th method on my blog
https://blog.studioblueplanet.net/?page_id=566

**Comment by Jacquers** [comment]
Thanks, that worked. 

The official TomTom software doesn't seem to work with the replaced driver.

**Comment by scubajorgen** [comment]
> The official TomTom software doesn't seem to work with the replaced driver.
Thanx. I made a note on my blog on this side effect
