### ISSUE TITLE
Support for the original race mode of Tomtom MySports

### ISSUE THREAD

**Issue by Albert1085** [scubajorgen/TomTomWatch#25]
Hey Jorgen,
first of all, I would like to thank you for this brilliant and very helpful software and your efforts and time spent on it. It figures out to become a very useful application because of the discontinuation of Tomtom MySports with the end of September. I'm one of several thousands actual users, which are affected by these circumstances. Myself even bought a replacement battery for this still quite functional sports watch so far...

To be as functional as possible like with the official Tomtom apps, I'm very interested to know, if your application supports the configuration and uploading of gpx-files respectively, which can be used for the so called "race mode" (see screenshot attached).
Is it possible, to define certain gpx-files to show up in the corresponding menu of the Tomtom sports watch in the end (the path is as followed in the watch's menu: select the sports type (e.g. running) => button press down => select "training" => race => select the favorite gps-track).

I would be very thankful, if you could give me some advice, because this is a core function which I use regularly with my watch.
Greets
Albert
![Screenshot MySports race mode menu](https://github.com/scubajorgen/TomTomWatch/assets/73784651/f9f4f4aa-fd35-48d2-a60e-b5ae00c7f564)

**Comment by scubajorgen** [comment]
Thanks for the response. It really is a nuisance to be dependent on a cloud service. If it is discontinued, you loose all your history. (I therefore wrote my own tracklogging ;-))

I am not really familiar with the racing function, apart from that the software supports an overview of the races on the watch.
My software supports the upload of routes. You can download the route list, add GPX files and save the list. But they are basically used for navigation

It seems that you propose to be able to select a route  for racing.
I only can select 'RECENTS' (apart from MYSPORTS and CREATE)... Will it present you a track?
I guess the function you propose might require a change of the watch software, which I cannot do.

**Comment by scubajorgen** [comment]
Not clear what the requirement is
