### ISSUE TITLE
Empty GPX file for swimming activities

### ISSUE THREAD

**Issue by lva** [scubajorgen/TomTomWatch#29]
Hello Jorgen,

Thanks a lot for your application! This will help to keep synchronizing my watch after TomTom discontinues their service later this month. It works great for my running activities.

I also use my watch (TomRom Runner 2) for tracking swimming sessions. The watch keeps track of every lap. I see the lap details in the TomTom Sports service and in Strava. The TCX file I can download from both services contains multiple Lap-entries.
Your application is generating an empty GPX file when I export the swim session. 

Do you have any advice?
Thanks!

**Comment by scubajorgen** [comment]
Dear Iva, I wrote this software for storing GPS tracks. To my knowledge the swimming feature does not store GPS coordates, but counts laps in the swimming pool. So GPX files are empty.
I don't know whether the GPX format supports lap counting... If you have a suggestion
Regards
Jörgen

**Comment by lva** [comment]
Hello Jorgen,

The watch doesn't store GPS coordinates in swimming activities. I checked the GPX standard and it does require GPS coordinates in the entries in the GPX file. So having a GPX file with swimming activities will not be possible. These need to be created in another file format. 

So unless you would be planning to support other file formats than GPX, then it looks like it will not be possible to use your software for swimming. But it's already a great help for the running activities and allows to synchronize activities even after TomTom will stop their services.

Best regards!
Lode
