### ISSUE TITLE
The tool does not detect the watch - Unable to claim interface: access denied

### ISSUE THREAD

**Issue by fabrizioolivieri** [scubajorgen/TomTomWatch#30]
Hello Jorgen,
I downloaded the zip e installed on my mac.
The install directory is `/Users/Fabrizio/Downloads/TomTomWatch/`
The app does not detect my watch.

Could be a problem of path? I manually changed the file tomtomwatch.properties with the following paths
```
gpxFilePath = /Users/Fabrizio/Downloads/TomTomWatch/GPX
ttbinFilePath = /Users/Fabrizio/Downloads/TomTomWatch/TTBIN
routeFilePath = /Users/Fabrizio/Downloads/TomTomWatch/ROUTE
```

Launching the app through the shell returns the following error:
`ERROR: USB Error: USB error 3: Unable to claim interface: Access denied (insufficient permissions)`

How can I solve it?

**Comment by scubajorgen** [comment]
The software uses usb4java. Should support OS-X, but I cannot try, so no support guaranteed.
Apparently you application has not the rights to use the USB bus.
On linux you have to grant privileges by adding rules to UDEV for a particular device.

**Comment by fabrizioolivieri** [comment]
Hello Jorgen,
I've managed to use the tool in my sons' Windows pc.
Thank you for developing it!
