### ISSUE TITLE
Enable  workout upload from JSON for Product ID: 0xde070000

### ISSUE THREAD

**Issue by krzysztof-michalak** [scubajorgen/TomTomWatch#31]
I have a TomTom Runner 3 watch (without music) which has the Product ID: 0xde070000 and allows uploading workouts from JSON to the watch without problems. So, my suggestion is to allow the upload for this watch by changing the line 2543 in TomTomWatchView.java from:

        if (id!=0xe0070000 && id!=0xd1070000)

to

        if (id!=0xe0070000 && id!=0xde070000 && id!=0xd1070000)

**Comment by scubajorgen** [comment]
Thanx for testing and reporting. Fixed it.
It would be nice if you could save a simulation set (= a dump of all the files) for your watch using the feature in the debug menu of tomtomwatch and send it to me in a zip. I can use it for testing then...
