### ISSUE TITLE
workouts from/to JSON file

### ISSUE THREAD

**Issue by lucenamarcio** [scubajorgen/TomTomWatch#35]
Good afternoon!

Firstly congratulations on the app, it's helping me a lot now that tomtom has deactivated the online service for its watches. My question, if you could help me, would be regarding personalized training, I have a tomtom spark 3 music that in the app is not enabling the menu to import json files. I would also like to know if editing the workouts.json file and after editing sending nboagain to the watch would the edited workout work on the watch?
![Screenshot_5](https://github.com/scubajorgen/TomTomWatch/assets/147876294/c0e3a141-a18b-48a5-a2c9-145b304ab331)
![Screenshot_6](https://github.com/scubajorgen/TomTomWatch/assets/147876294/a3a42580-de78-4615-982e-67a6c0172460)

**Comment by scubajorgen** [comment]
Dear, 

The reason I did not enable the function for the spark is that I simply didn't know if the spark supports it and  cannot test it. I don-t have a spark... 
It more or less is an experimental feature, so it is in the debug menu. 

I could easily make you a version of the software in which it is enabled so you can test it. I'll send it next week by mail. 

I would kindly request as a 'compensation' to save a simulation set, zip it and send it to me. A simulation set is a dump of all the files on the watch that I can use for testing in simulation mode as if the real watch was connected. 

Regards

Jörgen 


⁣Get BlueMail for Android ​

**Comment by lucenamarcio** [comment]
Good morning!

I would be grateful if you could send me a version where I can try to edit the training sessions on my watch. If I need to, I can also help with any tests that may be required, so attaching the simulation folder for my Spark as requested.
Still on the issue of training, although it is an experimental function, the idea would be to edit the workouts.json file and send it back to the watch, would this alone be enough for the watch to understand the training steps?

https://drive.google.com/drive/folders/1ChQ1vOrtQ4hfZQdhHAUx5NBaTwUk80V2?usp=sharing

**Comment by scubajorgen** [comment]
[Here ](https://download.studioblueplanet.net/TomTomWatch-test.jar)it is, should enable the menu item for Spark 3 Music.
Please let me know if this works for you.
Thanks for the simulation set btw :-)

**Comment by lucenamarcio** [comment]
Good afternoon!

It worked perfectly, I've even tested a personalized workout by directly editing the file and then sending it to the watch, I really appreciate it because after Tomtom deactivated the online application I was left with no way to create and edit my running workouts. Congratulations on the application, I am very satisfied.

Thanks!!
