### ISSUE TITLE
No heart rate data

### ISSUE THREAD

**Issue by MrBananaPants** [scubajorgen/TomTomWatch#36]
Is it possible to also extract the heart rate data and add it to the GPX file? I don't know if the heart rate data is stored in the TTIN file or somewhere else but maybe it's possible to extract it from somewhere in the memory and add it.

**Comment by scubajorgen** [comment]
In fact it stores the heartrate in extensions... 

⁣Get BlueMail for Android ​

**Comment by MrBananaPants** [comment]
So does that mean it's not possible?

**Comment by scubajorgen** [comment]
Hi

It is possible to get the heartrate out the TTBin

GPX does not by default allow for storage of the heartrate. However, GPX allows for extensions to store this kind of custon data. So I created extensions and implemented storage of speed, heartrate, tomtom fitnesspoints, etc. Just enable it in the properties file. It is called ugotme extensions or something like that. 
Garmin extensions are enabled by default but i think they don't support heartrate

However, the application that processes the GPX should be aware of the extensions

Jörgen 

⁣Get BlueMail for Android ​

**Comment by scubajorgen** [comment]
Example:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:u-gotMe="http://tracklog.studioblueplanet.net/gpxextensions/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" creator="TomTomWatch v1.5-87-g9808ddd (19.06.2020 @ 20:37:00 CEST)" version="1.1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://tracklog.studioblueplanet.net/gpxextensions/v2 http://tracklog.studioblueplanet.net/gpxextensions/v2/ugotme-gpx.xsd">
  <trk>
    <name>Track - TrailRunning</name>
    <desc>Created by: TomTomWatch v1.5-87-g9808ddd (19.06.2020 @ 20:37:00 CEST). Logged by: 'GPS Watch Jorgen 4' (serial: HL1496G01236). Logged as: TrailRunning.</desc>
    <trkseg>
      <trkpt lat="53.2526240" lon="6.5885485">
        <ele>-5.5</ele>
        <time>2020-08-18T18:17:57Z</time>
        <hdop>5</hdop>
        <extensions>
          <u-gotMe:speed>0.00</u-gotMe:speed>
          <u-gotMe:course>272.77</u-gotMe:course>
          <u-gotMe:hr>60</u-gotMe:hr>
          <u-gotMe:ehpe>1381</u-gotMe:ehpe>
          <u-gotMe:evpe>882</u-gotMe:evpe>
          <u-gotMe:ascend>0.0</u-gotMe:ascend>
          <u-gotMe:descend>0.0</u-gotMe:descend>
        </extensions>
      </trkpt>
      ...
```

Just enable extensions in tomtomwatch.properties by setting

```
garminGpxExtensions=false
ugotmeGpxExtensions=true
```
