### ISSUE TITLE
Workouts with the "cadence" intensity incorrectly imported/exported

### ISSUE THREAD

**Issue by krzysztof-michalak** [scubajorgen/TomTomWatch#38]
Workouts with the "cadence" intensity are incorrectly imported/exported. I attach a file with two JSONs (wrong/fixed) and a corresponding workout in 0x00be0001.bin file. Also, there are source files: original and corrected. Please verify and include in the repository if ok.
[20231025_cadence.zip](https://github.com/scubajorgen/TomTomWatch/files/13168551/20231025_cadence.zip)

**Comment by scubajorgen** [comment]
Thanx!! Merged.
