### ISSUE TITLE
GPS Quick Fix No longer works

### ISSUE THREAD

**Issue by scubadunc** [scubajorgen/TomTomWatch#42]
As of yesterday afternoon, the GPS quick fix no longer connects.  Is there any workaround?

**Comment by scubajorgen** [comment]
TomTom apparently stopped the service of providing the emphemeris files. 
As you can read in #33 the apparently provided the emphemeris files provided by the GPS chip supplier. However, we find another source for providing these files. So far I didn't find such a source. So if have an alternative...

**Comment by scubajorgen** [comment]
Ah! TomTom still provides the ephemeris service. Only the configuration service where to find this ephemeris service is no longer available. I hardcoded the ephemeris service URL in the code. We have to test if it works for all models, but I would suppose so.

**Comment by scubadunc** [comment]
Amazing work...Will you provide an updated zip file for download with the updated code? v1.91 perhaps?

**Comment by scubajorgen** [comment]
I'll make a release one of these days...

**Comment by Chillifish** [comment]
This is fantastic, I've just discovered this as about to set off for a run. Thanks so much for your work on this.

**Comment by scubajorgen** [comment]
Of course we do not know how long TomTom will continue to provide these ephemeris files... :-(
We still need a second source. So if anyone knows another source, let me know.

**Comment by CommodoreST** [comment]
I would suggest to use some kind of setting accessible from UI or config text file for ephemeris URL. Anyway, THANKS for your volunteer work on abandoned device that you don't even own.

**Comment by Paulipaule** [comment]
Might this be another source for the ehemeris files: [https://choaristudio.com/](url)

Thanks for your work on this project.

**Comment by nmainil** [comment]
Wondering if this is of any relevance to the issue as another source of ephemeris file: [https://github.com/felixge/node-ar-drone/issues/74#issuecomment-179910549](https://github.com/felixge/node-ar-drone/issues/74#issuecomment-179910549)

**Comment by deepsrm** [comment]
Would be nice a new release with eph file working, I don't think that tomtom is gonna close that backend service, maybe there are gps units using it 🤞

**Comment by scubajorgen** [comment]
Thanks. The choaristudio file is not identical to the TomTom file. I can try it though...
The parrot.com file nmainil refers to doesn't seem to work any more...

**Comment by mike5x3** [comment]
http://gpsquickfix.services.tomtom.com/fitness/sifgps.f2p7enc.ee 
http://choaristudio.com/agps/agps/f2p7enc.ee
http://mail.hieroglyphe.net/agps/agps/f2p7enc.ee

All identical - checked with:
https://www.duplichecker.com/page-comparison.php

**Comment by scubajorgen** [comment]
Thank you very much. Apparently I did not test well enough... I'll try again.
If so, we've got a backup :-)

BTW Release 1.10 binaries on [my blog](https://blog.studioblueplanet.net/software/tomtomwatch)

**Comment by krzysztof-michalak** [comment]
> Thank you very much. Apparently I did not test well enough... I'll try again. If so, we've got a backup :-)
> 
> BTW Release 1.10 binaries on [my blog](https://blog.studioblueplanet.net/software/tomtomwatch)

The files from TomTom and ChoariStudio WERE different until the end of October, more or less. Since the beginning of November though, they are identical.

I started using the files from the ChoariStudio recently and they are probably working ok (even the 14 days file!). However, I will have to test it some more, because I am using my watch in similar locations all the time and also the watch seems to cache the AGPS data somehow(?). One thing is, on my watch I originally found TWO identical files 0x00010100.bin and 0x00010102.bin with the same data from the .ee file. Second, even if I delete both files from the watch it keeps showing the ok sign (the check mark) in the AGPS status. Thus, I'll have to use the ChoariStudio files for longer and also use the watch farther from home to see if this really works.

By the way, I reconfigured my watch (without changing the program) by setting <ConfigURL>file:///t:/directory_name/config.json</ConfigURL> in 0x00f20000.bin so that I have config.json on my computer where I can set "service:ephemeris" to any URL (including a file on my computer using file:///). This allows me to test various files quickly by just replacing them on my computer.

Because the ChoariStudio has files for 1,3,5,7 and 14 days maybe the program could allow setting all those values in "quickFixDays" in the config? So far it only allows 3 and 7.

**Comment by scubajorgen** [comment]
> http://gpsquickfix.services.tomtom.com/fitness/sifgps.f2p7enc.ee 
> http://choaristudio.com/agps/agps/f2p7enc.ee 
> http://mail.hieroglyphe.net/agps/agps/f2p7enc.ee
> 
> All identical - checked with: https://www.duplichecker.com/page-comparison.php

@mike5x3 I just downloaded at 20:10 hours the files from TomTom (3, 7 days), choaristudio.com (1, 3, 7 and 14 days) and hieroglyph.net (1, 3, 7 and 14 days) and I find 

- choaristudio files and hieroglyph files are identical, name and content
- TomTom files **differ** from the other two, though their file structure and size seems to be the same and the contents for the most part but not entirely

Files are provided by the chip supplier at midnight. It might be that TomTom is stale...

I tried the 3 day  choarstudio file (and hence the hieroglyp file) in the TomTom watch and it resulted in a fix after **42 seconds**.
I tried the 7 days TomTom file on another watch:  fix after **9 seconds**
Consistent with earlier measurement I did under #33

Of course not very statistical but it seems choarstudio and hierglyp are for another chipset or so...

Could you please verify your findings?

**Comment by mike5x3** [comment]
> > http://gpsquickfix.services.tomtom.com/fitness/sifgps.f2p7enc.ee
> > http://choaristudio.com/agps/agps/f2p7enc.ee
> > http://mail.hieroglyphe.net/agps/agps/f2p7enc.ee
> > All identical - checked with: https://www.duplichecker.com/page-comparison.php
> 
> @mike5x3 I just downloaded at 20:10 hours the files from TomTom (3, 7 days), choaristudio.com (1, 3, 7 and 14 days) and hieroglyph.net (1, 3, 7 and 14 days) and I find
> 
> * choaristudio files and hieroglyph files are identical, name and content
> * TomTom files **differ** from the other two, though their file structure and size seems to be the same and the contents for the most part but not entirely
> 
> Files are provided by the chip supplier at midnight. So you might expect that TomTom (or the other two) could be stale...
> 
> However... I tried the 3 day choarstudio file (and hence the hieroglyp file) in the TomTom watch and it resulted in a fix after **42 seconds**. I tried the 7 days TomTom file on another watch: fix after **9 seconds** Consistent with earlier measurement I did under #33
> 
> Of course not very statistical but it seems choarstudio and hierglyp are for another chipset or so...
> 
> Could you please verify your findings?
> 
> I'll try again tomorrom morning: maybe TomTom and the others update the files at different times...

Yes, the TomTom file is stale:

curl -iks -X HEAD http://mail.hieroglyphe.net/agps/agps/f2p7enc.ee | grep Last-Modified
Last-Modified: Mon, 06 Nov 2023 19:24:33 GMT

curl -iks -X HEAD http://choaristudio.com/agps/agps/f2p7enc.ee | grep Last-Modified
Last-Modified: Mon, 06 Nov 2023 19:24:33 GMT

curl -iks -X HEAD http://gpsquickfix.services.tomtom.com/fitness/sifgps.f2p7enc.ee  | grep Last-Modified
Last-Modified: Mon, 06 Nov 2023 16:12:06 GMT

**Comment by krzysztof-michalak** [comment]
> Yes, the TomTom file is stale:

Not really. The TomTom file is (and has always been) generated every four hours at 00:12, 04:12, ..., 20:12 GMT. It does not seem this has changed recently.

The choaristudio is updated more frequently, but also more irregularly (see choaristudio_updates.txt for timestamps of updated files). I discovered, that choaristudio and tomtom sometimes differ and sometimes not, but I do not see any regularity (see choaristudio_differences.txt). NOTE: All timestamps are GMT+1 (my TomTom update hours are 01:12, 05:12, ..., 21:12).

[choaristudio_differences.txt](https://github.com/scubajorgen/TomTomWatch/files/13276123/choaristudio_differences.txt)

[choaristudio_updates.txt](https://github.com/scubajorgen/TomTomWatch/files/13276126/choaristudio_updates.txt)

**Comment by scubajorgen** [comment]
Clear! I find the timestamps of the update of choaristudio and hieroglype to be the same to the second. This might mean:
1. They use the timestamp of the provider of the files (the chip manufacturer)
2. Both choaristudio and hieroglype are the same or use the same data source
Since the timestamps differ from the tomtom timestamps I guess option 2...

**Comment by krzysztof-michalak** [comment]
Both choaristudio.com and hieroglyphe.net resolve to the same IP address: 198.100.148.158. Even though you can have multiple virtual WWW servers hosted at the same IP, I just assume they simply point to the same server and thus the files should be exactly the same.

**Comment by alois-git** [comment]
Indeed same people behind the two domain name.

https://who.is/whois/hieroglyphe.net
https://who.is/whois/choaristudio.com

French guy it looks like, I speak french, would be nice to know where he gets the file from :D

**Comment by krzysztof-michalak** [comment]
> The choaristudio makes android games that use the GPS :)

That's strange, because Android uses lto.dat files for A-GPS, not .ee files.

**Comment by scubajorgen** [comment]
I send a mail to choaristudio asking for information about the origin of the ephemeris files but they don't appear to respond

**Comment by LAHCEN47** [comment]
thank you so much for providing this workaround. you cant possibly imagine how much it means to me

**Comment by scubajorgen** [comment]
This can be closed.
