### ISSUE TITLE
interface already claimed

### ISSUE THREAD

**Issue by jonath35** [scubajorgen/TomTomWatch#43]
Hello

Since I installed ttwatch from ryanbinns in addition to TomTomWatch. I can't connect to the watch anymore. I get an error : 

ERROR: USB Error: An interface is already claimed

I don't know how to solve this error.

Thanks

**Comment by lva** [comment]
I had this error as well. This happened to me when the TomTom software was
still running and was connected to the watch.
Closing other applications that can connect to the watch like ttwatch or
TomTom before you start TomTomWatch should solve this.


Op do 2 nov. 2023 09:40 schreef jonath35 ***@***.***>:

**Comment by jonath35** [comment]
Thks for your reply,

I can't see any process running using htop..
I read somethings about kernel claimed but i don't know how to deal with it

Thks

**Comment by scubajorgen** [comment]
I guess you run it on Linux. 
To prove it isn't a clash between the softwares, restart your computer and only start TomTomWatch
To prove it isn't a rights issue, start is as root. If it works it is a rights issue

**Comment by jonath35** [comment]
restart and start as root doesn't change anything. There is a clash and it appears after the installation of the ryanbinns's ttwatch tools.

**Comment by scubajorgen** [comment]
AFAIK TomTomWatch does not alter anything on your computer. It uses USB4Java library to access USB.
The fact that TomTomWatch fails to work after installtin ttwatch suggests that ttwatch alters something. Please ask Ryan Binns about it.

**Comment by scubajorgen** [comment]
I am closing this one since I cannot solve it.
