### ISSUE TITLE
Tracked Activity download

### ISSUE THREAD

**Issue by daveM246** [scubajorgen/TomTomWatch#44]
Hi, Thanks for your great work on this. Is there a way to download tracked activity from the watch to a file? The 'Show Tracked Activity' menu works but I can't see a way to save this data to a file.
![image](https://github.com/scubajorgen/TomTomWatch/assets/112068533/d92875a7-3bcb-49ac-9381-7ef6b96f9040)
 I can copy and paste the data from the bottom panel in the app but is there a way to save the files from the watch to the /working/files folder?

**Comment by scubajorgen** [comment]
Nope! Only displays it to the text box. You can copy paste though...
