### ISSUE TITLE
Elevation data query

### ISSUE THREAD

**Issue by daveM246** [scubajorgen/TomTomWatch#45]
I have a TomTom Runner3 and it always showed elevation details in the gpx files created on the TomTom MySports site. I've tried using google height service and this works but is not as precise as the old system. 
My question is: Is the height data in the ttbin file extracted from the watch and if so can it be saved to the gpx file when that is created. Attached is a ttbin file with the gpx created by TomTomMySport and a gpx file created by TomTomWatch using the google height service.
[Height.zip](https://github.com/scubajorgen/TomTomWatch/files/13258088/Height.zip)

**Comment by scubajorgen** [comment]
Please read the part on height measuring of TomTom watches on [my blog](https://blog.studioblueplanet.net/software/tomtomwatch).

**Comment by scubajorgen** [comment]
Added to FAQ

**Comment by daveM246** [comment]
Thanks but I had read your blog. If there's no height data in the ttbin file then TomTom must have added the height data from their own 'height service'  when creating the gpx files. Thanks for the reply and thanks again for your work on TomTomWatch.

**Comment by scubajorgen** [comment]
That was my conclusion as well...
Unless one of the unknown messages which I didn't reverse engineer might contain the satellite height...
