### ISSUE TITLE
GPX file save not working

### ISSUE THREAD

**Issue by makosrepas** [scubajorgen/TomTomWatch#46]
Hi!
I'm not familiar in Java, but I compiled your source code v1.10. When I want to save a gpx file and push the save button, nothing happean. 
I used this command: mvn -Dmaven.test.skip package
What did I wrong?

Thank you, 
makosrepas

Windows 10
maven 3.9.5
JDK Development Kit 21.0.1

**Comment by scubajorgen** [comment]
Can you download files by presssing the Download button?

**Comment by makosrepas** [comment]
Ofcourse.
Now I'm trying your compiled version 1.10 from your website, this is working fine.
Thank You!

**Comment by scubajorgen** [comment]
Okay, solved then
