### ISSUE TITLE
ridimensionare le finestre

### ISSUE THREAD

**Issue by ranny70** [scubajorgen/TomTomWatch#47]
I can't enlarge the window with the red arrow and shrink the ones above. How can I do?
I have already tried with the screen resolution but nothing changes.
Thank you

![immagine](https://github.com/scubajorgen/TomTomWatch/assets/149330333/306c2752-00ff-49f9-a9fb-3c552fc6a105)

**Comment by scubajorgen** [comment]
Screen layout in Java with Swing in Netbeans is a pain in the ass. I therefore chose a fixed layout. 
Use a display size of 1920x1080 or play with compatibility mode.
