### ISSUE TITLE
Can't read serial number of TomTom Runner watch

### ISSUE THREAD

**Issue by DPAmes** [scubajorgen/TomTomWatch#48]
Serial number shows as "unknown" in the GUI.
TomTom Runner watch says it's "HC3483I-02783"

Startup log says:
>java -jar TomTomWatch.jar
i 2023-11-06 13:41:42  Settings read
i 2023-11-06 13:41:42  debugLevel=error
i 2023-11-06 13:41:42  debuggingMenu=false
i 2023-11-06 13:41:42  debugFilePath=.\working\files\
i 2023-11-06 13:41:42  gpxFilePath=.\working\gpx\
i 2023-11-06 13:41:42  routeFilePath=.\working\routes
i 2023-11-06 13:41:42  ttbinFilePath=.\working\ttbin
i 2023-11-06 13:41:42  autoSaveTtbin=true
i 2023-11-06 13:41:42  waypointLogTimeout=5000
i 2023-11-06 13:41:42  simulation=false
i 2023-11-06 13:41:42  simulationPath=.\working\simulation\
i 2023-11-06 13:41:42  trackSmoothingEnabled=true
i 2023-11-06 13:41:42  trackSmoothingQFactor=2.0
i 2023-11-06 13:41:42  trackCompressionEnabled=false
i 2023-11-06 13:41:42  trackCompressionMaxError=0.3
i 2023-11-06 13:41:42  heightService=none
i 2023-11-06 13:41:42  heightServiceKey=none
i 2023-11-06 13:41:42  mapService=osm
i 2023-11-06 13:41:42  mapServiceKey=none
i 2023-11-06 13:41:42  quickFixDays=7
i 2023-11-06 13:41:42  downloadAll=true
i 2023-11-06 13:41:42  ugotmeGpxExtensions=false
i 2023-11-06 13:41:42  garminGpxExtensions=true
**e 2023-11-06 13:41:43  ERROR: Error getting device serial number: USB error 8: U
nable to get string descriptor languages: Overflow**

Just reporting a trivial issue with an app that's a godsend, thank you!

**Comment by DPAmes** [comment]
I missed it in the "Closed" issues.

**Comment by scubajorgen** [comment]
This is a known issue and can be solved by installing another USB driver. See [my blog](https://blog.studioblueplanet.net/software/tomtomwatch) under 'Installation'
