### ISSUE TITLE
Does not work properly with first version of Tomtom watch 

### ISSUE THREAD

**Issue by Nico12345612** [scubajorgen/TomTomWatch#49]
I have the first version of the Tomtom watch and unfortunately, it does not work. When I connect the watch, nothing never appears in the main window. When clicking on Activity summary, I have the screen below, with some activities but with wrong data. Is it a known issue?

![image](https://github.com/scubajorgen/TomTomWatch/assets/141410723/248b91c6-dbc6-4608-b68c-dea5558e5809)

**Comment by scubajorgen** [comment]
Read the FAQ on github

**Comment by Nico12345612** [comment]
SOrry. Can be deleted if needed
