### ISSUE TITLE
I'm keep getting device not connected

### ISSUE THREAD

**Issue by vori1973** [scubajorgen/TomTomWatch#5]
I copied all info from Device , i'd like to be able to convert ttbin files to gpx . can i use deviceinfo.dat file with this app ?

**Comment by scubajorgen** [comment]
What type of watch do you have?
What exactly is the problem?
You can upload ttbin files (as downloaded for example with TomTom MySports) to the application using 'Load TTBIN' button (make  sure the file has the .ttbin extension), even without a watch connected. File will show up in the overview. You can select it and save it as GPX.
The deviceinfo.dat file is not used by the application.

**Comment by scubajorgen** [comment]
You probably have a Multisports. I just debugged the software for usage with the Multisports...

**Comment by vori1973** [comment]
Sorry for delay , Yes I have Multisports , so what should be done

**Comment by scubajorgen** [comment]
I bought myself a secondhand Multisports Cardio and used it to test and debug the software. If you download v1.3 from Github or [my site](http://blog.studioblueplanet.net/?page_id=566) it supports the Multisports :-)
If you still encounter problems, please let me know: what you try to do and what the result is.

**Comment by vori1973** [comment]
thanks , will try

**Comment by vori1973** [comment]
was no much luck for me it does not even see that device is connected , in other software that you had it was possible to point to a file that I think describe hardware or something , can it be done as well here . I'm using MAC and maybe it has some issue see the device ?

**Comment by scubajorgen** [comment]
Auch. I can test under Windows and Linux, but not under mac. In principle the USB library (libusb4java) I use should support OSX 32 and 64 bits, but I don't know the details. Maybe a rights issue? 
I guess you refer to the Garmin software for the hardware description? That file is only used for retrieving the serial of the device...
