### ISSUE TITLE
Sync time: Enable GPS to sync to GPS time

### ISSUE THREAD

**Issue by kedar-1** [scubajorgen/TomTomWatch#52]
Hello,

as well as others owners I'm happy I'm able to use my Tomtom watch after the vendor abonding step so I'm sending a **HUGE thank you**.

My watch is out of time sync because I'didnt charged for several days.
Right now I'm trying to sync time using computer clock thru Device - Sync Time Offset menu but I have received an error below:

_Watch clock more than 5 minutes out of sync. Enable GPS to sync to GPS time_

What exactly is needed to do to: Enable GPS to sync to GPS time?

Using 1.10 version on Windows 10.

**Comment by scubajorgen** [comment]
Hi
Thanks for the response. 
Sync isn't really time sync but time zone sync. Please read the FAQ on github. 
Time is synced when using activity logging
Jörgen 


⁣Get BlueMail for Android ​

**Comment by kedar-1** [comment]
Hi,

thanks for explanation.
I was not aware that the activity sync time in watch.

Closing
