### ISSUE TITLE
Feature request: auto convert to GPX (and FIT)

### ISSUE THREAD

**Issue by kedar-1** [scubajorgen/TomTomWatch#53]
Hi,

all activities are downloaded to the folder according the time of activity.
I had connected MapMyfitness to the Sport Connect software and I'm able to find GPX and FIT files in the same folder as ttbin.

It will be helpful to allow in TomTom Watch to automatically download & convert to GPX for all ttbin files and save the files to the same folder.

There is a project to allow export from ttbin to  [FIT](https://github.com/ryanbinns/ttwatch/tree/master) so if its technically possible I vote for export to FIT using the checkbox.

**Comment by scubajorgen** [comment]
I guess this one is a double of #51.

All the download folders you can define in the tomtomwatch.properties.

I am familiar with the FIT file format and even created a Java Fitreader library. FIT basically is a format meant to be used by devices. The spec mentions:
_The Flexible and Interoperable Data Transfer (FIT) protocol is a format designed specifically for the storing and sharing of data that originates from sport, fitness and health devices. It is specifically designed to be compact, interoperable and extensible. This section describes the FIT file structure and interpretation._
Given this purpose, it wouldn't be my primary choice to convert the TomTom data to.
GPX has the advantage that it is XML and hence easily editable (which I occasionally do if I forgot to terminate an activity).
