### ISSUE TITLE
I can't download more than 12 files (last 3 months)

### ISSUE THREAD

**Issue by larchers** [scubajorgen/TomTomWatch#54]
I use the app since 2 days... so maybe I miss somethings. (Version 1.10)

When I connect the watch, I can download only last 12 activities, only running, from the last 3 months. 
If I list all activities, I can see biking activities, since 2019, but I find no way to transfert them to my computer.

**Comment by scubajorgen** [comment]
Please read the FAQ on Github

⁣Get BlueMail for Android ​

**Comment by larchers** [comment]
I'm sorry, I misread the FAQ ... I had all the information in front of me.
Thank you for all your hard work.
