### ISSUE TITLE
Just gratitude for the alternative software.

### ISSUE THREAD

**Issue by snooppr** [scubajorgen/TomTomWatch#56]
Reviewed as of the end of January 2024.
My TomTom Runner Cardio watch. I updated them: I bought a new strap for them in China and a battery with a larger capacity than the standard one.
OS GNU/Linux deb. I downloaded the binary from the link from the blog. The software worked right out of the box without instructions or anything else! Workouts are downloaded, deleted, GPS is updated - quickGPX works.
Thank you very much for your efforts! The watch has received a second life.

**Comment by scubajorgen** [comment]
Thanx for your feedback :-)

**Comment by scubajorgen** [comment]
I close this one. No work to be done here ;-)
