### ISSUE TITLE
Battery percentage

### ISSUE THREAD

**Issue by ltguillaume** [scubajorgen/TomTomWatch#57]
Would it be possible to display the current charge percentage of the battery? I found it pretty annoying of the original TomTom software that there wasn't a proper indication, but it at least showed when the device was fully charged. It would be really nice to have an indication (ideally the raw percentage) in TomTomWatch as well.

**Comment by scubajorgen** [comment]
As you can see in my [reverse engineering page](https://blog.studioblueplanet.net/software/tomtomwatch/tomtom-watch-file-system) I did not find a proper function to read out the current battery level. 
The battery level however seems to be logged every 30 seconds when performing an activity. So I could add it to the GPX (I don't see a real benefit from that other than to track how fast the battery discharges over time)...

You write '_but it at least showed when the device was fully charged_'. Where did it show this?

**Comment by scubajorgen** [comment]
During activities battery level is logged. I don't know how to get the battery level when the device is attached to the PC...
