### ISSUE TITLE
Appreciation and Feature Request - Proxy Configuration

### ISSUE THREAD

**Issue by Pompom51150** [scubajorgen/TomTomWatch#58]
Dear Jorgen van der Velde,

I would like to express my sincere appreciation for your outstanding work on the program that enables the retrieval of activities from TomTom watches. It has been a tremendous help for many users, including myself, following the removal of the software by TomTom. Your contribution has truly been our savior, and I want to thank you warmly for that.

The program you have developed works remarkably well in retrieving activities. However, I am facing a challenge due to the network configuration in my environment. My setup utilizes a proxy, preventing me from updating QuickGPS and displaying the map background for activities.

Is it possible to consider adding a feature to configure the proxy in the software? This would be greatly beneficial for users like me who are on networks with specific configurations.

I understand that you may receive numerous requests and suggestions, but if you could consider this enhancement, it would make your program even more comprehensive and useful for a diverse user base.

Thank you again for your hard work and for providing a valuable solution to a challenging situation. I look forward to your future updates.

Best regards,

**Comment by scubajorgen** [comment]
Thanks for the feedback. 
A proxy wouldn't be that much work, however I cannot test it. I'll look into it... 



⁣Get BlueMail for Android ​

**Comment by scubajorgen** [comment]
I can test it using Burp suite, which acts like a proxy. I'll implement it one of these days...

**Comment by scubajorgen** [comment]
I am trying to get things working using the Java system settings. However, it works for the ephemeris file, and for the google map, not for the OSM map. The library jxviewer does not seem to support it, though under the hood it appears to use the same java.net.URL to make the connection as for retrieving the ephemeris file.

You can easily try it yourself using command line parameter

java -Dhttp.proxyHost=proxy.example.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.example.com -Dhttps.proxyPort=8080 -jar TomTomWatch.jar

See also: https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

**Comment by scubajorgen** [comment]
Please let me know if it works for you, @Pompom51150

**Comment by scubajorgen** [comment]
I close this, although I could only test the situation without credentials...
