### ISSUE TITLE
14 day QuickGPS fix works

### ISSUE THREAD

**Issue by CommodoreST** [scubajorgen/TomTomWatch#59]
Not an issue. I've seen it mentioned somewhere. I just wanted to confirm that it works. I don't know how reliable it is on different devices or in different parts of the world. I'm not a Java developer so I had to use hex editor to change http address to http://choaristudio.com/agps/f2p14enc.ee. It works fine. Checked every day for 14 days with fast fix and on 15th day I got slow fix. My device is TomTom Spark 3.

**Comment by scubajorgen** [comment]
Done: 1.12

⁣Get BlueMail for Android ​
