### ISSUE TITLE
Recommendations for java runtime software and environment respectively

### ISSUE THREAD

**Issue by Albert1085** [scubajorgen/TomTomWatch#60]
Hello Jorgen,

first of all, I've to tell you, that I'm really excited about the extension of the usability of the Tomtom Sports Watch because of your outstanding freeware. Thanks so much once more for your efforts and initiative regarding to the redevelopment of the software. It was delightful to see, that the latest version is already now 1.10 (from 5.11.2023)!

Nevertheless, I'm quite unexperienced with java running software under Windows. This is why I would like to ask you, if you could recommend a certain program, preferably a low perfomance consuming software.

I would be very thankful for your recommendation.
Regards
Albert

**Comment by CommodoreST** [comment]
https://whichjdk.com/ - Adoptium is recommended choice. I use IBM Semeru Runtime. It's not recommended but OpenJ9 VM is supposed to have lower RAM usage.

**Comment by scubajorgen** [comment]
I use Oracle [Java 1.8.0_331](https://www.java.com/nl/download/ie_manual.jsp).
You probably can also use OpenJDK.
You can download JRE or JDK. Basically you only need a JRE (JDK is required for developing software)
I don't know TomTomWatch runs under version 11

**Comment by scubajorgen** [comment]
In fact it is already in the FAQ...
