### ISSUE TITLE
Normalize the size of the program window

### ISSUE THREAD

**Issue by snooppr** [scubajorgen/TomTomWatch#62]
There are inconveniences when working in the software.
The problem affects software on GNU/Linux and Windows.

After deleting activities or updating GPSQuick, you need to look at the message log (finish of operations), but it does not fit on screens with a resolution of 1366x768, you have to hold down “alt + left mouse button” and move the program window up/down beyond the screen area, this is inconvenient.

Please reduce the program window vertically, or create a button: auto-fit the window to the screen size (usually a square icon at the top of the program window next to the cross/close and underscore/minimize).

**Comment by scubajorgen** [comment]
Unfortunatelly layouting on Java progrmming language isn't that easy so I cannot do this.
In an era of HD and 4K screens the software I won't put energy in supporing all kind of legacy equipment. Sorry.
