### ISSUE TITLE
GPX upload error

### ISSUE THREAD

**Issue by 123flodirk** [scubajorgen/TomTomWatch#63]
hi
I tried uploading a saved gpx file (\working\gpx\) to runkeeper and runningahead but getting a error that the file is bad. No explanation to the error.

I have tried loading the file in  https://gpx.studio/ also got error on the gpx file. Same error that it is not a valid gpx file

I must be doing something immensily silly wrong...I attached to gpx file 

 using 1.12 for a runner 2 watch on windows 11. The app works well othewise.

kudos for your app saving my tomtomwatch :)

[running_20240526_description.zip](https://github.com/scubajorgen/TomTomWatch/files/15448065/running_20240526_description.zip)

**Comment by 123flodirk** [comment]
I loaded the GPX file in the validator to test it:
https://www.freeformatter.com/xml-validator-xsd.html
-> the error in the file is :
```
`The Prefix "u-gotMe" For Element "u-gotMe:trackpointExtension" Is Not Bound., Line '10', Column '41'.
The Prefix "u-gotMe" For Element "u-gotMe:trackpointExtension" Is Not Bound.`
```

**Comment by 123flodirk** [comment]
something to do with this?
https://blog.studioblueplanet.net/software/u-gotme-2/u-gotme

**Comment by scubajorgen** [comment]
It is comes in handy if you send me the file, because I cannot guess what went wrong with the file. 

The u-gotme extensions I invented for myself and won't be widely supported. But they shouln't bother futher processing either. So I guess something went wrong. 

You can disable the extensions in the properties file. 

⁣Get BlueMail for Android ​

**Comment by scubajorgen** [comment]
Sorry, I see you sent the file. 
Apparently you enabled the gpxtpx extensions as well as the u-gotme extensions. 
Please disable the u-gotme extensions. 
It can be done in tomtomwatch.properties.

I will add something on the faq about the extensions

⁣Get BlueMail for Android ​

**Comment by 123flodirk** [comment]
hi thanks, makes sense , but I do not think I changed the flag and it is by default "false".
```
# Enable GPX extensions (various metadata on track, tracksegment and track points)
ugotmeGpxExtensions = false
```

but it seems to add the ugotme extensions even though the flag says false (I am using your Jar downloaded from your website)?  See attached properties file.

thanks again for your response!
[tomtomwatchproperties.zip](https://github.com/scubajorgen/TomTomWatch/files/15464757/tomtomwatchproperties.zip)

**Comment by scubajorgen** [comment]
In that case it is an issue. That might explain the extensions are empty... 
Thanks for reporting. I'll repair it, but it make take a while

⁣Get BlueMail for Android ​

**Comment by scubajorgen** [comment]
Yeah, I changed a bit on the extensions recently, so the bug could have been resolved with it :-) 
I'll check the source and close the issue in a week or two

⁣Get BlueMail for Android ​

**Comment by scubajorgen** [comment]
> no rush :)
> 
> I downloaded your 1.10 version and that works fine.
> 
> [TomTomWatch1.10.zip](https://blog.studioblueplanet.net/wp-content/files/tomtomwatch/TomTomWatch1.10.zip)

Wait a minute, you encountered the problem in 1.12 and  you downgraded to 1.10 to solve the problem??

**Comment by scubajorgen** [comment]
Yup, the problem was introduced in version v1.11; solved it

**Comment by 123flodirk** [comment]
Ja dat klopt
Grt
Flori
