### ISSUE TITLE
Watch not recognized on Mac

### ISSUE THREAD

**Issue by LucAwater** [scubajorgen/TomTomWatch#65]
I have tried hooking up my tomtom sports watch to your app on a macbook (M1, os: Sonoma 14.5).

It doesn't seem to recognize the watch though. For Windows, I saw someone mentioning Zadig to install missing drivers, but I think that works a little differently on mac. Do you have any ideas how I can still connect or if it's even possible?

Thanks!

**Comment by scubajorgen** [comment]
Unfortunatelly **I do not support Apple or Mac** (in fact I hate uhm... am not fond of Apple, but that is another story)

Please ask Fipps who raised issue #64 recently but got the software working.

Please, if you get it working on Mac tell me how that I'll put in the FAQ.

**Comment by scubajorgen** [comment]
Duplicate of #64
