### ISSUE TITLE
No window sizing (Linux Ubuntu 18.04) and Textfields do resize on long filepath

### ISSUE THREAD

**Issue by machinaeXlasse** [scubajorgen/TomTomWatch#7]
The window(frame) size seems to be fixed to one size (somewhere around 1300px width)

Window can not be resized. Pulling the edges seems to be disabled and maximize button is missing.

The window size is no problem until one or more textfields are extended by a long filepath. This leeds to Buttons getting out of reach because the window doesn't resize accordingly.

I guess textfields are not supposed to resize. They do whenever I choose a custom filepath to upload a route to the watch. (Same behaviour when choosing filepath for TTBIN or GPX files)

This might be an Ubuntu-desktop (Gnome based) Issue.

Thanks for the great tool! Besides this issue it works wonderfully out of the box for Ubuntu 18.04!

![resizeandtextfieldissue](https://user-images.githubusercontent.com/15941745/42164190-88f30f70-7e05-11e8-82a8-39401ba3dd13.png)

**Comment by scubajorgen** [comment]
I've seen this issue. Recently I changed the layout and I will check if the problem persists.
Thanx for reporting.

**Comment by scubajorgen** [comment]
Within the new layout the text fields can cope with long content without resizing (checked under Windows).
Therefore no longer an issue. I'll check under Linux one of these days.
I don't intend to make the application resizeable.
