### ISSUE TITLE
Route name field should update when the Route GPX field changes 

### ISSUE THREAD

**Issue by ABelliqueux** [scubajorgen/TomTomWatch#9]
When choosing a route GPX file to upload to the watch, the "Route name" field should update to reflect the new filename. This would avoid the user (that's me :)) to inadvertently upload different routes with the same name.

Thanks for your software and efforts anyway !

**Comment by scubajorgen** [comment]
My initial idea was not to update the route name if the user already had entered something. However, I think you are right: it is more intuitive to replace the name when having chosen a file.

**Comment by ABelliqueux** [comment]
@scubajorgen I'm using a Tomtom Runner 3 and it works fine with your software.

**Comment by scubajorgen** [comment]
Ah! I see that the Runner 3 also support routes.... I thought only the Adventurer. Could you please send the product ID of this device as displayed at the top of TomTom watch?
